### ISSUE TITLE
Gesture typing not working even after copying the library.

### ISSUE THREAD

**Issue by jgmGit** [Hardslog/platform_packages_inputmethods_EnhancedIME#4]
I am trying to run the application of a `Lineage OS 14.1` on Nexus 6p (`Android 7.1.1`). I installed the application and I copied the library  `libjni_latinimegoogle.so` from `opengapps` to `\system\lib64` folder. Still I am not able to make`gesture typing` work. Is there something else that needs to be done ?

**Comment by Hardslog** [comment]
That should be it, although I haven't looked at it lately but have a feeling that this will not work on Android 7.x

If you could pastebin me a logcat I can take a look.  Alternatively I did make a "hacked" version of this app where gesture typing will work fine on Nougat based roms.  It's the exact same apk file as on the release pages but I swapped out the AOSP latinime.so file with the Google one that has Gesture typing.  You can get that from here: https://www.dropbox.com/s/rodhdipur2g7o3t/EnhancedIME-1.0.4_swipe.apk?dl=0

**Comment by jgmGit** [comment]
How do I take a logcat specifically of the gesture typing ?  I am not getting any particular messages when I disable and enable gesture typing.

This is the genereic.

```
02-02 16:33:38.907 32304-32311/? I/art: Debugger is no longer active
02-02 16:33:38.907 32304-32311/? I/art: Starting a blocking GC Instrumentation
02-02 16:33:38.979 32304-32304/? I/LatinIME: Hardware accelerated drawing: true
02-02 16:33:39.035 32304-32304/? W/InputAttributes: No editor info for this field. Bug?
02-02 16:33:39.044 32304-32321/? I/LatinIME:LogUtils: Dictionary info: dictionary = contacts.en_US ; version = 1486048661 ; date = 1486048661
02-02 16:33:39.045 32304-32321/? I/LatinIME:LogUtils: Dictionary info: dictionary = userunigram.en_US ; version = 1486049619 ; date = ?
02-02 16:33:39.053 32304-32321/? I/LatinIME:LogUtils: Dictionary info: dictionary = UserHistoryDictionary.en_US ; version = 1486045057 ; date = 1486047025
02-02 16:33:39.065 32304-32321/? I/LatinIME:LogUtils: Dictionary info: dictionary = main:en ; version = 54 ; date = 1414726273
02-02 16:33:39.188 32304-32323/? I/Adreno: QUALCOMM build                   : 74df444, I409c65498b
                                           Build Date                       : 06/22/16
                                           OpenGL ES Shader Compiler Version: XE031.08.00.02
                                           Local Branch                     : N16
                                           Remote Branch                    : 
                                           Remote Branch                    : 
                                           Reconstruct Branch               : 
02-02 16:33:39.193 32304-32323/? I/OpenGLRenderer: Initialized EGL, version 1.4
02-02 16:33:39.193 32304-32323/? D/OpenGLRenderer: Swap behavior 1

```

**Comment by jgmGit** [comment]
Why don't you include the hacked version in the repo ?

**Comment by Hardslog** [comment]
The hacked version isn't included because the gesture library isn't open source.
